===
# Semantic Type
- name: type/patch
  color: '#42c2f5'
- name: type/minor
  color: '#f54242'
- name: type/major
  color: 'fc0505'
- name: type/break
  color: 'f6412d'
# Area
- name: area/docs
  color: '2d66f6'
- name: area/apps
  color: '42f566'
- name: area/web-ui
  color: 'daa520'
- name: area/libs
  color: 'f542f5'