---
area/docs:
  - changed-files:
      - any-glob-any-file: Docs/**/*
area/apps:
  - changed-files:
      - any-glob-any-file: apps/**/*
area/web-ui:
  - changed-files:
      - any-glob-any-file: aps/sinlessgames-ui/**/*
      - any-glob-any-file: apps/sinlessgames-ui-e2e/**/*
area/libs:
  - changed-files:
      - any-glob-any-file: libs/**/*