---
#
# Area of the Repo
#
area/docs:
  - changed-files:
      - any-glob-to-any-file: Docs/**/*.md
      - any-glob-to-any-file: /**/README.md
  - base-branch: main

area/apps:
  - changed-files:
      - any-glob-to-any-file: apps/**/*
  - base-branch: main

area/web-ui:
  - changed-files:
      - any-glob-to-any-file: aps/sinlessgames-ui/**/*
      - any-glob-to-any-file: apps/sinlessgames-ui-e2e/**/*
  - base-branch: main

area/libs:
  - changed-files:
      - any-glob-to-any-file: libs/**/*
  - base-branch: main

area/taskfile:
  - changed-files:
      - any-glob-to-any-file: .taskfiles/**/*.yaml
      - any-glob-to-any-file: Taskfile.yaml
  - base-branch: main

area/packageJSON:
  - changed-files:
      - any-glob-to-any-file: /**/package.json
  - base-branch: main

#
# Branches
#
branches:
  - name: develop
    labels:
      - name: "branch: develop"
  - name: feature
    labels:
      - name: "branch: feature"
  - name: bugfix
    labels:
      - name: "branch: bugfix"
  - name: hotfix
    labels:
      - name: "branch: hotfix"
  - name: release
    labels:
      - name: "branch: release"
  - name: fix
    labels:
      - name: "branch: fix"
  - name: main
    labels:
      - name: "branch: main"

#
# Types
#
pull-requests:
  - types: [opened, reopened]
    labels:
      - name: "type: todo"
      - name: "type: patch"
      - name: "type: minor"
      - name: "type: major"
      - name: "type: break"


issues:
  - types: [opened, reopened]
    labels:
      - name: "type: todo"
      - name: "type: patch"
      - name: "type: minor"
      - name: "type: major"
      - name: "type: break"