---
# Branches
- name: "branch:develop"
  color: 'f54242'
- name: "branch:feature"
  color: 'f54242'
- name: "branch:bugfix"
  color: 'f54242'
- name: "branch:hotfix"
  color: 'f54242'
- name: "branch:release"
  color: 'f54242'
- name: "branch:fix"
  color: 'f54242'
- name: "branch:main"
  color: 'f54242'

# Semantic Type
- name: type/patch
  color: '#42c2f5'
- name: type/minor
  color: '#f54242'
- name: type/major
  color: 'fc0505'
- name: type/break
  color: 'f6412d'
- name: type/todo
  color: 'f5a542'

# Area
- name: area/docs
  color: '2d66f6'
- name: area/apps
  color: '42f566'
- name: area/web-ui
  color: 'daa520'
- name: area/libs
  color: 'f542f5'
- name: area/taskfile
  color: '0e8a16'
- name: area/packageJSON
  color: 'f5a542'

# Misc
- name: 'todo comment'
  color: 'f54242'