[
  {
    "language": "CSS",
    "extensions": [
      ".css"
    ],
    "markers": {
      "block": [
        {
          "start": "/\\*",
          "end": "\\*/"
        }
      ],
      "line": "//"
    }
  },
  {
    "language": "HTML",
    "extensions": [
      ".html"
    ],
    "markers": {
      "block": [
        {
          "start": "<!--",
          "end": "-->"
        }
      ]
    }
  },
  {
    "language": "JavaScript",
    "extensions": [
      ".js",
      ".mjs",
      ".cjs",
      ".jsx"
    ],
    "markers": {
      "block": [
        {
          "start": "/\\*",
          "end": "\\*/"
        }
      ],
      "line": "//"
    }
  },
  {
    "language": "JSON5",
    "extensions": [
      ".json5"
    ],
    "markers": {
      "block": [
        {
          "start": "/\\*",
          "end": "\\*/"
        }
      ],
      "line": "//"
    }
  },
  {
    "language": "JSON with Comments",
    "extensions": [
      ".jsonc",
      ".json5",
      ".json"
    ],
    "markers": {
      "block": [
        {
          "start": "/\\*",
          "end": "\\*/"
        }
      ],
      "line": "//"
    }
  }
  {
    "language": "Markdown",
    "extensions": [
      ".md",
      ".markdown",
      ".mdx"
    ],
    "markers": {
      "block": [
        {
          "start": "<!--",
          "end": "-->"
        }
      ]
    }
  },
  {
    "language": "Sass",
    "extensions": [
      ".sass"
    ],
    "markers": {
      "block": [
        {
          "start": "/\\*",
          "end": "\\*/"
        }
      ],
      "line": "//"
    }
  },
  {
    "language": "SCSS",
    "extensions": [
      ".scss"
    ],
    "markers": {
      "block": [
        {
          "start": "/\\*",
          "end": "\\*/"
        }
      ],
      "line": "//"
    }
  },
  {
    "language": "TSX",
    "extensions": [
      ".tsx"
    ],
    "markers": {
      "block": [
        {
          "start": "/\\*",
          "end": "\\*/"
        }
      ],
      "line": "//"
    }
  },
  {
    "language": "TypeScript",
    "extensions": [
      ".ts"
    ],
    "markers": {
      "block": [
        {
          "start": "/\\*",
          "end": "\\*/"
        }
      ],
      "line": "//"
    }
  },
  {
    "language": "YAML",
    "extensions": [
      ".yaml",
      ".yml"
    ],
    "markers": {
      "block": [
        {
          "start": "/*",
          "end": "*/"
        }
      ],
      "line": "#"
    }
  }
]