---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

# vars:
# env:
# includes:

tasks:
  default: task -l

  init:
    desc: Initialize The Project
    cmds:
      - cmd: echo Initializing the project
      - cmd: npm install -g npm@10.5.0
        silent: true
      - cmd: npm add --global nx@latest
        silent: true
      