name:  Nx CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install pnpm
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: nrwl/nx-set-shas@v4
      # This line is needed for nx affected to work when CI is running on a PR
      # - run: git branch --track main

      - run: npx nx-cloud record -- nx format:check --package-manager=pnpm
      - run: npx nx affected -t lint test build e2e-ci --package-manager=pnpm
