---
    name: 'Labeler'

    # TODO: figure out why this doesn't work
    # 
    # It works on labeling github Issues, but not PRs
    #
    # URL: https://github.com/actions/labeler
    
    on:
      - pull_request
    
    jobs:
      labeler:
        name: Labeler
        runs-on: ubuntu-latest
        permissions:
          contents: read
          pull-requests: write
          issues: write
        steps:
          - name: Labeler
            uses: actions/labeler@v5
            with:
              configuration-path: .github/labeler.yaml